### ISSUE TITLE
[Bug] autoStart props 

### ISSUE THREAD

**Issue by jass-trix** [danielMensah/react-native-smart-carousel#1]
Hi @danielMensah  
You've made wrong documentation here.
It should be 'autoPlay' props not 'autoStart'
Wondering why the carousel won't work. It seems because of you wrongly documented it

Any way i have a suggestion for you to give user props for the image resizeMode 
because i have to change manually inside the package to fix resizeMode

**Comment by danielMensah** [comment]
Hi @jass-trix 
Thank you for spotting the error in the documentation and for your suggestion. I will try to make the image resizeMode changes whenever I can.
